"""BaselineThresholds — data-driven anomaly thresholds from historical data.

Sources of baseline data (in priority order):

1. **GHA run baseline** (``baseline.json`` generated by ``run_baseline.py``):
   Workflow success rates, timing, and per-group scrape metrics.

2. **Historical stats.json snapshots** (from git history):
   ``frontend/public/stats.json`` is committed daily by the GHA stats workflow.
   Each snapshot contains ``divergence``, ``silence``, and ``lusa_dependency``
   metrics.  This module mines the git history to compute mean/std for each.

3. **Hardcoded fallback defaults**: Used when no other data is available.

Usage:
    thresholds = BaselineThresholds()
    div_threshold = thresholds.get_divergence_threshold()
    sil_threshold = thresholds.get_silence_anomaly_threshold(current_avg_7d=33.0)
    lusa_threshold = thresholds.get_lusa_dependency_threshold()
    print(thresholds.describe())
"""

from __future__ import annotations

import json
import logging
import math
import subprocess
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ── Hardcoded fallback defaults ─────────────────────────────────────────────
FALLBACK_DIVERGENCE_THRESHOLD = 0.35
FALLBACK_SILENCE_MULTIPLIER = 2.0
FALLBACK_SILENCE_MEAN_TODAY = 50.0
FALLBACK_SILENCE_STD_TODAY = 30.0
FALLBACK_LUSA_THRESHOLD = 80.0

# Path to stats.json relative to project root
_STATS_JSON_REPO_RELATIVE = "frontend/public/stats.json"

# Max snapshots to load from git history (90 days of daily commits)
_MAX_HISTORICAL_SNAPSHOTS = 90


# ═════════════════════════════════════════════════════════════════════════════
#  Helpers
# ═════════════════════════════════════════════════════════════════════════════


def _compute_series_stats(values: list[float]) -> dict[str, float | int | None]:
    """Compute mean, std, min, max, n for a list of floats.

    Returns a dict with keys ``mean``, ``std``, ``min``, ``max``, ``n``.
    ``mean`` and ``std`` are ``None`` when the list is empty.
    """
    n = len(values)
    if n == 0:
        return {"mean": None, "std": None, "min": None, "max": None, "n": 0}
    mean = sum(values) / n
    if n < 2:
        return {"mean": mean, "std": 0.0, "min": min(values), "max": max(values), "n": n}
    variance = sum((x - mean) ** 2 for x in values) / (n - 1)
    return {
        "mean": mean,
        "std": math.sqrt(variance),
        "min": min(values),
        "max": max(values),
        "n": n,
    }


# ═════════════════════════════════════════════════════════════════════════════
#  BaselineThresholds
# ═════════════════════════════════════════════════════════════════════════════


class BaselineThresholds:
    """Data-driven anomaly thresholds from GHA baseline + historical stats.

    Parameters
    ----------
    baseline_path:
        Path to the ``baseline.json`` file (from ``run_baseline.py``).
        Defaults to ``data/baseline.json``.
    project_root:
        Project root directory (used to find ``frontend/public/stats.json``).
        Defaults to the parent of the ``backend/`` directory.
    """

    def __init__(
        self,
        baseline_path: str | Path | None = None,
        project_root: str | Path | None = None,
    ) -> None:
        self._raw: dict = {}
        self._loaded = False

        # ── Resolve project root ───────────────────────────────────────────
        if project_root is None:
            # Default: repo root (parent of backend/ directory)
            project_root = Path(__file__).resolve().parent.parent.parent.parent
        self._project_root = Path(project_root)

        # ── Load baseline.json ─────────────────────────────────────────────
        if baseline_path is None:
            baseline_path = self._project_root / "data" / "baseline.json"

        path = Path(baseline_path)
        if path.exists():
            try:
                self._raw = json.loads(path.read_text(encoding="utf-8"))
                self._loaded = True
                logger.info("Loaded GHA baseline from %s", path)
            except (json.JSONDecodeError, OSError) as exc:
                logger.warning("Failed to load GHA baseline from %s: %s", path, exc)

        if not self._loaded:
            logger.info("No GHA baseline found — using hardcoded fallback thresholds")

        # ── Load historical stats history (lazy, on first threshold access) ──
        self._stats_history: dict | None = None

    # ── Metadata ────────────────────────────────────────────────────────────

    @property
    def is_loaded(self) -> bool:
        """Whether baseline.json was successfully loaded."""
        return self._loaded

    @property
    def generated_at(self) -> str:
        """ISO timestamp of when the baseline was generated."""
        return self._raw.get("generated_at", "") if self._loaded else ""

    @property
    def days_analyzed(self) -> int:
        """Number of days of history the baseline covers."""
        return self._raw.get("days_analyzed", 0) if self._loaded else 0

    @property
    def n_snapshots(self) -> int:
        """Number of historical stats.json snapshots mined from git."""
        hist = self._ensure_stats_history()
        return hist.get("n_snapshots", 0)

    # ═════════════════════════════════════════════════════════════════════════
    #  Historical stats.json mining
    # ═════════════════════════════════════════════════════════════════════════

    def _ensure_stats_history(self) -> dict:
        """Lazy-load and return the stats history cache.

        Returns a dict with keys like::

            {
                "n_snapshots": 42,
                "divergence": {
                    "global_avg": {"values": [...], "mean": 0.3, "std": 0.1, "n": 42},
                    "per_outlet": {
                        "publico": {"values": [...], "mean": 0.3, ...},
                        ...
                    },
                },
                "silence": {
                    "today": {"values": [...], "mean": 50, "std": 30, ...},
                    "avg_7d": {"values": [...], "mean": 33, "std": 15, ...},
                },
                "lusa_dependency": {
                    "global_pct": {"values": [...], "mean": 90, "std": 10, ...},
                    "per_outlet": {
                        "publico": {"values": [...], "mean": 85, ...},
                        ...
                    },
                },
            }
        """
        if self._stats_history is not None:
            return self._stats_history

        self._stats_history = self._compute_stats_history()
        return self._stats_history

    def _compute_stats_history(self) -> dict:
        """Mine historical stats.json snapshots from git history.

        Runs ``git log`` and ``git show`` to extract divergence, silence,
        and Lusa dependency metrics from every commit that modified
        ``frontend/public/stats.json``.

        Returns a dict with computed mean/std for each metric (see
        ``_ensure_stats_history`` for structure), or an empty dict if git
        is not available or no history exists.
        """
        stats_path = self._project_root / _STATS_JSON_REPO_RELATIVE
        if not stats_path.exists():
            logger.info("stats.json not found at %s — cannot mine history", stats_path)
            return {}

        # ── Get commit hashes that modified stats.json ─────────────────────
        try:
            result = subprocess.run(
                [
                    "git", "log", "--all", "--follow",
                    "--format=%H", "--max-count", str(_MAX_HISTORICAL_SNAPSHOTS),
                    "--", str(stats_path),
                ],
                capture_output=True, text=True, check=True,
                cwd=self._project_root,
            )
            hashes = [h.strip() for h in result.stdout.strip().split("\n") if h.strip()]
        except (subprocess.SubprocessError, FileNotFoundError):
            logger.info("Git not available or not a git repo — skipping stats history mining")
            return {}

        if not hashes:
            logger.info("No git history found for %s", _STATS_JSON_REPO_RELATIVE)
            return {}

        logger.info("Mining %d historical stats.json snapshots from git…", len(hashes))

        # ── Extract metrics from each snapshot ──────────────────────────────
        div_avgs: list[float] = []
        div_per_outlet: dict[str, list[float]] = {}
        sil_todays: list[float] = []
        sil_avgs: list[float] = []
        lusa_pcts: list[float] = []
        lusa_per_outlet: dict[str, list[float]] = {}

        for h in hashes:
            try:
                content = subprocess.run(
                    ["git", "show", f"{h}:{_STATS_JSON_REPO_RELATIVE}"],
                    capture_output=True, text=True, check=True,
                    cwd=self._project_root,
                ).stdout
                data = json.loads(content)
            except (subprocess.SubprocessError, json.JSONDecodeError, ValueError):
                continue

            # ── Divergence ─────────────────────────────────────────────────
            div = data.get("divergence", {}) or {}
            gavg = div.get("global_avg")
            if gavg is not None:
                div_avgs.append(float(gavg))

            per_outlet_div = div.get("per_outlet", {}) or {}
            for oid, od in per_outlet_div.items():
                oavg = od.get("avg") if isinstance(od, dict) else None
                if oavg is not None:
                    div_per_outlet.setdefault(oid, []).append(float(oavg))

            # ── Silence ────────────────────────────────────────────────────
            sil = data.get("silence", {}) or {}
            today = sil.get("today")
            if today is not None:
                sil_todays.append(float(today))
            avg_7d = sil.get("avg_7d")
            if avg_7d is not None:
                sil_avgs.append(float(avg_7d))

            # ── Lusa dependency ────────────────────────────────────────────
            dep = data.get("lusa_dependency", {}) or {}
            gpct = dep.get("global_pct")
            if gpct is not None:
                lusa_pcts.append(float(gpct))

            per_outlet_dep = dep.get("per_outlet", {}) or {}
            for oid, od in per_outlet_dep.items():
                opct = od.get("pct") if isinstance(od, dict) else None
                if opct is not None:
                    lusa_per_outlet.setdefault(oid, []).append(float(opct))

        # ── Compute aggregate stats ────────────────────────────────────────
        result: dict[str, Any] = {"n_snapshots": len(hashes)}

        # Divergence
        div_result: dict[str, Any] = {}
        if div_avgs:
            div_result["global_avg"] = _make_series(div_avgs)
        if div_per_outlet:
            div_result["per_outlet"] = {
                oid: _make_series(vals) for oid, vals in div_per_outlet.items()
            }
        if div_result:
            result["divergence"] = div_result

        # Silence
        sil_result: dict[str, Any] = {}
        if sil_todays:
            sil_result["today"] = _make_series(sil_todays)
        if sil_avgs:
            sil_result["avg_7d"] = _make_series(sil_avgs)
        if sil_result:
            result["silence"] = sil_result

        # Lusa dependency
        lusa_result: dict[str, Any] = {}
        if lusa_pcts:
            lusa_result["global_pct"] = _make_series(lusa_pcts)
        if lusa_per_outlet:
            lusa_result["per_outlet"] = {
                oid: _make_series(vals) for oid, vals in lusa_per_outlet.items()
            }
        if lusa_result:
            result["lusa_dependency"] = lusa_result

        logger.info(
            "Stats history mining complete: %d snapshots, "
            "%d divergence samples, %d silence samples, %d lusa samples",
            len(hashes), len(div_avgs), len(sil_todays), len(lusa_pcts),
        )

        return result

    # ═════════════════════════════════════════════════════════════════════════
    #  Divergence baseline
    # ═════════════════════════════════════════════════════════════════════════

    def get_divergence_threshold(self, outlet_id: str | None = None) -> float:
        """Return the divergence anomaly threshold (mean + 1sigma).

        When historical stats exist, uses the distribution of global_avg
        (or per-outlet avg if *outlet_id* is given) to compute the threshold.

        Falls back to ``FALLBACK_DIVERGENCE_THRESHOLD`` (0.35).
        """
        hist = self._ensure_stats_history()
        divergence = hist.get("divergence")
        if not divergence:
            return FALLBACK_DIVERGENCE_THRESHOLD

        # Per-outlet threshold
        if outlet_id is not None:
            per_outlet = divergence.get("per_outlet", {})
            outlet_stats = per_outlet.get(outlet_id)
            if outlet_stats and outlet_stats["mean"] is not None:
                return max(0.10, outlet_stats["mean"] + outlet_stats["std"])

        # Global threshold
        global_stats = divergence.get("global_avg")
        if global_stats and global_stats["mean"] is not None:
            return max(0.10, global_stats["mean"] + global_stats["std"])

        return FALLBACK_DIVERGENCE_THRESHOLD

    def get_divergence_baseline(self, outlet_id: str | None = None) -> dict:
        """Return full divergence baseline as a dict with keys::

            {"mean": ..., "std": ..., "min": ..., "max": ..., "n": ...}

        Returns per-outlet stats if *outlet_id* is given, else global stats.
        Returns empty dict if no historical data.
        """
        hist = self._ensure_stats_history()
        divergence = hist.get("divergence")
        if not divergence:
            return {}

        if outlet_id is not None:
            per_outlet = divergence.get("per_outlet", {})
            return dict(per_outlet.get(outlet_id, {}))

        global_stats = divergence.get("global_avg", {})
        return dict(global_stats)

    # ═════════════════════════════════════════════════════════════════════════
    #  Silence baseline
    # ═════════════════════════════════════════════════════════════════════════

    def get_silence_std_dev_multiplier(self) -> float:
        """Return the silence anomaly multiplier.

        When historical stats exist, derives the multiplier from the
        historical coefficient of variation (std / mean) of ``today``
        values.  A stable metric (low CV) yields a tighter multiplier
        (~1.5), while a volatile metric (high CV) yields a looser one
        (up to 3.0).  Falls back to 2.0.
        """
        hist = self._ensure_stats_history()
        silence = hist.get("silence")
        if not silence:
            return FALLBACK_SILENCE_MULTIPLIER

        today_stats = silence.get("today")
        if today_stats and today_stats["mean"] and today_stats["mean"] > 0:
            cv = today_stats["std"] / today_stats["mean"]
            # CV < 0.5 -> stable -> 1.5sigma; CV > 1.5 -> volatile -> 3.0sigma
            multiplier = 1.5 + min(cv, 2.0) * 0.75
            return round(multiplier, 2)

        return FALLBACK_SILENCE_MULTIPLIER

    def get_silence_baseline(self) -> dict:
        """Return full silence baseline as a dict::

            {
                "today": {"mean": ..., "std": ..., ...},
                "avg_7d": {"mean": ..., ...},
            }

        Returns empty dict if no historical data.
        """
        hist = self._ensure_stats_history()
        silence = hist.get("silence", {})
        return dict(silence)

    def get_silence_anomaly_threshold(
        self,
        current_avg_7d: float | None = None,
        sigma: float | None = None,
    ) -> float:
        """Return the silence anomaly threshold.

        Uses the historical distribution of ``today`` values:
            threshold = base + sigma * std_today

        Parameters
        ----------
        current_avg_7d:
            If provided and historical data exists, uses the current 7-day
            average as the base instead of the historical mean.
        sigma:
            Number of standard deviations.  Defaults to
            ``get_silence_std_dev_multiplier()``.

        Returns a float threshold.  Falls back to the old formula
        (``base + 2.0 * max(base, 1.0)``) when no historical data exists.
        """
        if sigma is None:
            sigma = self.get_silence_std_dev_multiplier()

        hist = self._ensure_stats_history()
        silence = hist.get("silence")
        today_stats = silence.get("today") if silence else None

        if today_stats and today_stats["mean"] is not None:
            mean_today = today_stats["mean"]
            std_today = today_stats["std"]
            base = current_avg_7d if current_avg_7d is not None else mean_today
            return base + sigma * std_today

        # Fallback: old formula
        base = current_avg_7d if current_avg_7d else FALLBACK_SILENCE_MEAN_TODAY
        return base + FALLBACK_SILENCE_MULTIPLIER * max(base, 1.0)

    # ═════════════════════════════════════════════════════════════════════════
    #  Lusa dependency baseline
    # ═════════════════════════════════════════════════════════════════════════

    def get_lusa_dependency_baseline(self, outlet_id: str | None = None) -> dict:
        """Return Lusa dependency stats as a dict::

            {"mean": ..., "std": ..., "min": ..., "max": ..., "n": ...}

        Returns per-outlet stats if *outlet_id* is given, else global stats.
        Returns empty dict if no historical data.
        """
        hist = self._ensure_stats_history()
        lusa = hist.get("lusa_dependency")
        if not lusa:
            return {}

        if outlet_id is not None:
            per_outlet = lusa.get("per_outlet", {})
            return dict(per_outlet.get(outlet_id, {}))

        global_stats = lusa.get("global_pct", {})
        return dict(global_stats)

    def get_lusa_dependency_threshold(self, outlet_id: str | None = None) -> float:
        """Return the Lusa dependency anomaly threshold (mean + 1.5sigma).

        Falls back to ``FALLBACK_LUSA_THRESHOLD`` (80.0) when no historical
        data is available.
        """
        hist = self._ensure_stats_history()
        lusa = hist.get("lusa_dependency")
        if not lusa:
            return FALLBACK_LUSA_THRESHOLD

        stats = None
        if outlet_id is not None:
            per_outlet = lusa.get("per_outlet", {})
            stats = per_outlet.get(outlet_id)
        else:
            stats = lusa.get("global_pct")

        if stats and stats["mean"] is not None:
            return min(100.0, stats["mean"] + 1.5 * stats["std"])

        return FALLBACK_LUSA_THRESHOLD

    # ═════════════════════════════════════════════════════════════════════════
    #  GHA baseline (from baseline.json)
    # ═════════════════════════════════════════════════════════════════════════

    def get_scrape_articles_baseline(self, group: str) -> dict[str, Any]:
        """Return per-group scrape articles baseline from GHA data.

        Returns ``{"mean": ..., "std": ..., ...}`` or empty dict if the
        group is not in baseline.json.
        """
        if not self._loaded:
            return {}
        groups = self._raw.get("scrape_groups", {})
        return dict(groups.get(group, {}))

    def get_scrape_anomaly_threshold(
        self, group: str, sigma: float = 2.0
    ) -> float | None:
        """Return lower-bound anomaly threshold for scrape articles.

        Threshold = max(0, mean - sigma * std).

        Returns ``None`` when no baseline is available for the group.
        """
        baseline = self.get_scrape_articles_baseline(group)
        if not baseline or baseline.get("mean") is None:
            return None
        mean: float = baseline["mean"]
        std: float = baseline.get("std", 0.0) or 0.0
        return max(0.0, mean - sigma * std)

    def get_workflow_success_baseline(self, workflow_id: str) -> float | None:
        """Return the expected success rate (0-100) for a given workflow.

        Returns ``None`` if the workflow is not in baseline.json.
        """
        if not self._loaded:
            return None
        wfs = self._raw.get("workflows", {})
        wf = wfs.get(workflow_id)
        if wf and "success_rate" in wf:
            return float(wf["success_rate"])
        return None

    def get_daily_articles_threshold(
        self, sigma: float = 2.0
    ) -> dict[str, float | None]:
        """Return a per-run articles volume threshold from GHA scrape groups.

        Sums the per-group scrape baselines (``news``, ``international``,
        etc.) to derive an expected articles-per-run count, then computes a
        lower-bound anomaly threshold::

            {
                "expected_mean": 450.0,
                "expected_std": 50.0,
                "threshold": 350.0,   # mean - sigma * std
            }

        .. note::

           The baseline values are **per scrape run**, not daily totals.
           A group like ``news`` that runs every 30 minutes will have a
           much smaller per-run mean than its daily total.  This method
           is intended as a quick sanity check; for daily volume anomaly
           detection the 7-day timeline from ``stats.timelines`` is more
           accurate and self-contained.

        Returns all-``None`` values when no baseline is loaded.
        """
        if not self._loaded:
            return {"expected_mean": None, "expected_std": None, "threshold": None}

        groups = self._raw.get("scrape_groups", {})
        if not groups:
            return {"expected_mean": None, "expected_std": None, "threshold": None}

        # Sum per-group means and pooled std (sum of variances under
        # independence assumption — gives a conservative pooled std)
        total_mean = 0.0
        total_variance = 0.0
        n_groups = 0

        for gname, gstats in groups.items():
            m = gstats.get("mean")
            s = gstats.get("std")
            if m is not None and s is not None:
                total_mean += float(m)
                total_variance += float(s) ** 2
                n_groups += 1

        if n_groups == 0:
            return {"expected_mean": None, "expected_std": None, "threshold": None}

        pooled_std = math.sqrt(total_variance) if total_variance > 0 else 0.0
        threshold = max(0.0, total_mean - sigma * pooled_std)
        return {
            "expected_mean": round(total_mean, 1),
            "expected_std": round(pooled_std, 1),
            "threshold": round(threshold, 1),
        }

    # ═════════════════════════════════════════════════════════════════════════
    #  Summary
    # ═════════════════════════════════════════════════════════════════════════

    def describe(self) -> str:
        """Return a human-readable summary of all available baselines."""
        parts: list[str] = []
        parts.append("BaselineThresholds Report")
        parts.append("=" * 50)
        parts.append("")

        # GHA baseline
        parts.append(f"GHA baseline.json: {'YES' if self._loaded else 'NO (fallback mode)'}")
        if self._loaded:
            parts.append(f"  Generated: {self.generated_at}")
            parts.append(f"  Days analyzed: {self.days_analyzed}")
        parts.append("")

        # Historical stats
        hist = self._ensure_stats_history()
        n = hist.get("n_snapshots", 0)
        parts.append(f"Historical stats.json snapshots: {n}")
        parts.append("")

        if n > 0:
            # Divergence
            div = hist.get("divergence")
            if div:
                parts.append("--- Divergence ---")
                ga = div.get("global_avg", {})
                if ga.get("mean") is not None:
                    parts.append(
                        f"  Global avg: mean={ga['mean']:.3f}  "
                        f"sigma={ga['std']:.3f}  n={ga['n']}"
                    )
                    parts.append(
                        f"  Threshold: {self.get_divergence_threshold():.3f}"
                    )
                    per_outlet = div.get("per_outlet", {})
                    if per_outlet:
                        parts.append("  Per-outlet:")
                        top = sorted(
                            per_outlet.items(),
                            key=lambda x: x[1].get("mean", 0) or 0,
                            reverse=True,
                        )[:5]
                        for oid, st in top:
                            m = st.get("mean", "?")
                            s = st.get("std", "?")
                            parts.append(f"    {oid}: mean={m:.3f} sigma={s:.3f}")
                parts.append("")

            # Silence
            sil = hist.get("silence")
            if sil:
                parts.append("--- Silence ---")
                today_st = sil.get("today", {})
                if today_st.get("mean") is not None:
                    parts.append(
                        f"  Today: mean={today_st['mean']:.1f}  "
                        f"sigma={today_st['std']:.1f}  n={today_st['n']}"
                    )
                avg7d_st = sil.get("avg_7d", {})
                if avg7d_st.get("mean") is not None:
                    parts.append(
                        f"  Avg 7d: mean={avg7d_st['mean']:.1f}  "
                        f"sigma={avg7d_st['std']:.1f}  n={avg7d_st['n']}"
                    )
                multiplier = self.get_silence_std_dev_multiplier()
                parts.append(f"  Multiplier: {multiplier:.2f}sigma")
                parts.append("")

            # Lusa
            lusa = hist.get("lusa_dependency")
            if lusa:
                parts.append("--- Lusa Dependency ---")
                gp = lusa.get("global_pct", {})
                if gp.get("mean") is not None:
                    parts.append(
                        f"  Global: mean={gp['mean']:.1f}%  "
                        f"sigma={gp['std']:.1f}%  n={gp['n']}"
                    )
                    parts.append(
                        f"  Threshold: {self.get_lusa_dependency_threshold():.1f}%"
                    )
                parts.append("")

        # GHA scrape baselines
        if self._loaded:
            groups = self._raw.get("scrape_groups", {})
            if groups:
                parts.append("--- Scrape Groups (GHA baseline) ---")
                for gname, gstats in sorted(groups.items()):
                    m = gstats.get("mean", "?")
                    s = gstats.get("std", "?")
                    parts.append(f"  {gname}: mean={m} sigma={s}")

        return "\n".join(parts)

    def __repr__(self) -> str:
        return (
            f"BaselineThresholds("
            f"baseline_loaded={self._loaded}, "
            f"n_snapshots={self.n_snapshots})"
        )


# ═════════════════════════════════════════════════════════════════════════════
#  Internal helpers
# ═════════════════════════════════════════════════════════════════════════════


def _make_series(values: list[float]) -> dict[str, Any]:
    """Build a series dict from a list of values.

    Returns summary stats without the raw values list to avoid retaining
    thousands of data points in memory across the historical stats cache.
    Only ``mean``, ``std``, ``min``, ``max``, ``n`` are returned — the
    threshold methods only use these aggregates.
    """
    return dict(_compute_series_stats(values))
